# Generated by Django 3.1.7 on 2023-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suscripcion', '0003_auto_20231022_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='categoria',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='modalidad',
            field=models.CharField(choices=[('Gym', 'Gym'), ('Spin', 'Spin'), ('Yoga', 'Yoga'), ('Gym + Spin', 'Gym + Spin'), ('Gym + Yoga', 'Gym + Yoga'), ('Gym + Spin + Yoga', 'Gym + Spin + Yoga')], default='Gym', max_length=20),
        ),
    ]
