# Generated by Django 3.1.7 on 2023-12-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DetalleSuscripcion', '0002_auto_20231225_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesuscripcion',
            name='estado',
        ),
    ]
