# Generated by Django 3.1.7 on 2024-01-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetalleSuscripcion', '0003_remove_detallesuscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesuscripcion',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='detallesuscripcion',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
