# Generated by Django 3.1.7 on 2024-01-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
        ('Venta', '0003_auto_20231219_2302'),
        ('DetalleVenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Producto.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='idVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Venta.venta'),
        ),
    ]
