# Generated by Django 3.1.7 on 2024-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('idFrase', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('frase', models.CharField(max_length=1000)),
            ],
        ),
    ]
