# Generated by Django 3.1.7 on 2023-10-24 00:03

import apps.Cliente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_auto_20231023_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=apps.Cliente.models.upload_to),
        ),
    ]
