# Generated by Django 3.1.7 on 2024-01-06 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_auto_20231227_1200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Venta', '0003_auto_20231219_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='idCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
