# Generated by Django 3.1.7 on 2023-12-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20231219_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='estado',
        ),
    ]
