# Generated by Django 3.1.7 on 2024-01-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_auto_20231227_1200'),
        ('Registro', '0004_auto_20240106_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='idCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Cliente.cliente'),
        ),
    ]
