# Generated by Django 3.1.7 on 2023-12-26 23:20

from django.db import migrations
import random

def create_pins(apps, schema_editor):
    AvailablePIN = apps.get_model('AvailablePIN', 'AvailablePIN')
    pins = [AvailablePIN(pin=i, isAssigned=False) for i in range(100, 1000)]
    random.shuffle(pins)
    AvailablePIN.objects.bulk_create(pins)

class Migration(migrations.Migration):

    dependencies = [
        ('AvailablePIN', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_pins, reverse_code=migrations.RunPython.noop),
    ]
